### ISSUE TITLE
Lumix GX9 - No Stream autostart

### ISSUE THREAD

**Issue by lentemoore** [peci1/lumix-link-desktop#15]
Hi,

I just tested lumix-link-desktop with the panasonic lumix DC-GX9 and it works! Hurray! I am using Linux, and the camera has the IP Address 192.168.54.1.
Connecting works in Firefox and chromium, but Firefox only throws errors. Chromium allows recording and shooting. I honestly don't understand what the other buttons are supposed to do.
What doesn't work is the java live stream from the camera. I had to start it separately in a terminal (java -jar ./StreamViewer.jar). But the stream works, though I haven't found out to tell my Linux to use it as webcam input, which would be nice ^^

So, yeah, more a report, but also one issue. Anything I can do to help solve that?

**Comment by peci1** [comment]
Thanks for the report, glad to hear it works.

Regarding the java viewer not launching - do you launch the whole app via the `Control.sh` script? How exactly? What's the console output?

**Comment by peci1** [comment]
I did not try to route the camera stream to the Linux camera framework (probably video4linux). And as I don't have a use-case for that, I won't implement it (though I'm open to pull requests offering this functionality).

**Comment by lentemoore** [comment]
Ah, alright. The control.sh file isn't included in the current release zip, which I used (I just opened control.html). With the script it opens the java stream window too, but it only shows video with chromium, it's a white void when using firefox.

Firefox also throws this output:
`err_rejecttry { Object.defineProperty(screen, "availTop", { value: 0 }); } catch (e) {} try { Object.defineProperty(screen, "availLeft", { value: 0 }); } catch (e) {} try { Object.defineProperty(screen, "availWidth", { value: 1760 }); } catch (e) {} try { Object.defineProperty(screen, "availHeight", { value: 990 }); } catch (e) {} try { Object.defineProperty(screen, "colorDepth", { value: 24 }); } catch (e) {} try { Object.defineProperty(screen, "pixelDepth", { value: 24 }); } catch (e) {} try { Object.defineProperty(navigator, "hardwareConcurrency", { value: 8 }); } catch (e) {} try { Object.defineProperty(navigator, "appVersion", { value: "5.0 (X11)" }); } catch (e) {} try { Object.defineProperty(navigator, "doNotTrack", { value: "unspecified" }); } catch (e) {} try { window.screenY = 0 } catch (e) { } try { window.screenTop = 0 } catch (e) { } `

I'd love to offer a pull request, but sadly I have no idea how to implement something like that (my code level is very low). Just thought it might be a nice feature (but yeah, I probably would also only use it once a year).

**Comment by lentemoore** [comment]
As using the script does open the stream, I'll close this issue.

**Comment by peci1** [comment]
You're right, control.sh wasn't part of the release ZIP. I fixed that.
