### ISSUE TITLE
Missing:  Set date and time

### ISSUE THREAD

**Issue by HJarausch** [peci1/lumix-link-desktop#5]
Hi,

is there a means to set the date and time on the Lumix camera.
It must be possible remote because the official Panasonic Image App is able to do so.
Many thanks for a hint,
Helmut

**Comment by peci1** [comment]
Thanks for the suggestion.

Fixed in 5a85903a1a5aa95018d829976ba368aff627c8d9.

If you're gonna use the manual time setting, be aware that it always expects time without DST applied (e.g. now I'm in timezone GMT+0200 thanks to DST, but it expects time in GMT+0100).

Setting time doesn't work if you have camera menu open, it works only in the shooting mode.

**Comment by HJarausch** [comment]
Many, many thanks, Martin,
Happy Easter to you,
Helmut.

**Comment by HJarausch** [comment]
Hi Martin,
I cannot get a connection to my FZ1000 at all.
On the camera I did
Wi-Fi -> Wi-Function -> new connection -> remote control
Using the WiFi-Manager on my Android tablet I can connect the camera which shows up as
FZ1000-A6BEED IP 192.168.54.10
(Going from there to the official Pansonic image app does work)

I've opened requests.html with my browser (momument browser) which asks me  for the IP
of the camera.
I've entered  192.168.54.10 as is shown by the WiFi-Manager but it seems as if there is no
connection to the camera.
Trying to synchronize time I get
http://192.168.54.10/cam/cgi?mode=setsetting?type=clock&value=....
couldn't be loaded

What am I missing?
Many thanks for a hint,
Helmut

**Comment by peci1** [comment]
Helmut, do the other controls (like shooting an image) work? 

What happens if you enter the address http://192.168.54.10/cam/cgi into your browser?

**Comment by HJarausch** [comment]
Hi, it was my fault. The WiFi manager showed the IP 192.168.54.10 but a network scanner revealed another active IP 192.168.54.1 . Taking this one resolves the problem.
Thanks,
Helmut

**Comment by peci1** [comment]
Good, thanks for reporting ;)
