### ISSUE TITLE
Support Request

### ISSUE THREAD

**Issue by unresolvedhost** [peci1/lumix-link-desktop#7]
Can you please make it work for the Lumix G7 camera?

**Comment by IdrisTheDragon** [comment]
although it's not listed in the readme, I have had success using this with the G7, it just requires a little bit of fiddling to get it right if i remember correctly.

**Comment by unresolvedhost** [comment]
![Lumix](https://user-images.githubusercontent.com/35327061/73013711-d4f5e280-3e3e-11ea-9009-40a228816ada.PNG)

Can you please tell me how? I connected my camera wifi to my computer with remote shooting and view and then I ran control.bat file with the IP 192.168.54.1 with subnet 24. I have no video output on the screen.

**Comment by IdrisTheDragon** [comment]
I can't remember, was a long time ago, I will have a play about at some point and see if I can work it out again.

**Comment by unresolvedhost** [comment]
Okay Let me know if you do. Thank you

**Comment by unresolvedhost** [comment]
I was able to control G7 with the web interface by changing ip address in requests.html, But no Live view. Does the G7 use the same UDP ports as GH3?

**Comment by unresolvedhost** [comment]
![image](https://user-images.githubusercontent.com/35327061/73190772-7d13f000-414c-11ea-9106-41b77fce6ec8.png)
I was able to get the live stream just by inspecting the startstream button (http://192.168.54.1/cam.cgi?mode=startstream&value=49199) but the stream size looks so small and freezes after few seconds.

**Comment by peci1** [comment]
Hi, I'm sorry for joining here late... Does closing this issue mean you solved all the problems you had? What did you have to do? It might be valuable information for other users...

Thanks for reporting ;)
